// <auto-generated />
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(GiteDbContext))]
    [Migration("20260113191017_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Gite", b =>
                {
                    b.Property<int>("GiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("giteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiteId"));

                    b.Property<int>("CapacityMax")
                        .HasColumnType("int")
                        .HasColumnName("capacityMax");

                    b.Property<int>("CapacityMin")
                        .HasColumnType("int")
                        .HasColumnName("capacityMin");

                    b.Property<string>("GiteAddress")
                        .IsRequired()
                        .HasColumnType("char(100)")
                        .HasColumnName("giteAddress")
                        .IsFixedLength();

                    b.Property<int>("GiteNumber")
                        .HasColumnType("int")
                        .HasColumnName("giteNumber");

                    b.Property<decimal>("GitePrice")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("gitePrice");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasColumnName("isAvailable");

                    b.HasKey("GiteId");

                    b.HasIndex("GiteNumber")
                        .IsUnique();

                    b.ToTable("tblGite", (string)null);
                });

            modelBuilder.Entity("Domain.Models.GiteAmenities", b =>
                {
                    b.Property<int>("GiteId")
                        .HasColumnType("int")
                        .HasColumnName("giteId");

                    b.Property<bool?>("Balcony")
                        .HasColumnType("bit")
                        .HasColumnName("balcony");

                    b.Property<bool?>("Bath")
                        .HasColumnType("bit")
                        .HasColumnName("bath");

                    b.Property<bool?>("Chair")
                        .HasColumnType("bit")
                        .HasColumnName("chair");

                    b.Property<bool?>("Cuttlery")
                        .HasColumnType("bit")
                        .HasColumnName("cuttlery");

                    b.Property<bool?>("Desk")
                        .HasColumnType("bit")
                        .HasColumnName("desk");

                    b.Property<bool?>("EatingArea")
                        .HasColumnType("bit")
                        .HasColumnName("eatingArea");

                    b.Property<bool?>("HairDryer")
                        .HasColumnType("bit")
                        .HasColumnName("hairDryer");

                    b.Property<bool?>("Kettle")
                        .HasColumnType("bit")
                        .HasColumnName("kettle");

                    b.Property<bool?>("MiniFridge")
                        .HasColumnType("bit")
                        .HasColumnName("miniFridge");

                    b.Property<bool?>("RoomService")
                        .HasColumnType("bit")
                        .HasColumnName("roomService");

                    b.Property<bool?>("Shower")
                        .HasColumnType("bit")
                        .HasColumnName("shower");

                    b.Property<bool?>("SmallChild")
                        .HasColumnType("bit")
                        .HasColumnName("smallChild");

                    b.Property<bool?>("Sofa")
                        .HasColumnType("bit")
                        .HasColumnName("sofa");

                    b.Property<bool?>("SofaBed")
                        .HasColumnType("bit")
                        .HasColumnName("sofaBed");

                    b.Property<bool?>("Toiletries")
                        .HasColumnType("bit")
                        .HasColumnName("toiletries");

                    b.Property<bool?>("Wifi")
                        .HasColumnType("bit")
                        .HasColumnName("wifi");

                    b.HasKey("GiteId");

                    b.ToTable("tblGiteAmenities", (string)null);
                });

            modelBuilder.Entity("Domain.Models.GiteBed", b =>
                {
                    b.Property<int>("GiteBedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("giteBedId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiteBedId"));

                    b.Property<int>("Amount1PrBed")
                        .HasColumnType("int")
                        .HasColumnName("amount1PrBed");

                    b.Property<int>("Amount2PrBed")
                        .HasColumnType("int")
                        .HasColumnName("amount2PrBed");

                    b.Property<int>("Amount3PrBed")
                        .HasColumnType("int")
                        .HasColumnName("amount3PrBed");

                    b.Property<string>("BedSort")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bedSort");

                    b.Property<int>("GiteId")
                        .HasColumnType("int")
                        .HasColumnName("giteId");

                    b.HasKey("GiteBedId");

                    b.HasIndex("GiteId");

                    b.ToTable("tblGiteBed", (string)null);
                });

            modelBuilder.Entity("Domain.Models.GiteAmenities", b =>
                {
                    b.HasOne("Domain.Models.Gite", "Gite")
                        .WithOne("Amenities")
                        .HasForeignKey("Domain.Models.GiteAmenities", "GiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gite");
                });

            modelBuilder.Entity("Domain.Models.GiteBed", b =>
                {
                    b.HasOne("Domain.Models.Gite", "Gite")
                        .WithMany("Beds")
                        .HasForeignKey("GiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gite");
                });

            modelBuilder.Entity("Domain.Models.Gite", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Beds");
                });
#pragma warning restore 612, 618
        }
    }
}
