// <auto-generated />
using System;
using LegacyMonolith.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegacyMonolith.Migrations
{
    [DbContext(typeof(DbMarconnes))]
    partial class DbMarconnesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LegacyMonolith.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.HasKey("AccountId");

                    b.ToTable("tblAccount");
                });

            modelBuilder.Entity("LegacyMonolith.Models.Gite", b =>
                {
                    b.Property<int>("GiteNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiteNumber"));

                    b.Property<int?>("CapacityMax")
                        .HasColumnType("int");

                    b.Property<int?>("CapacityMin")
                        .HasColumnType("int");

                    b.Property<string>("GiteAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("GitePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("bit");

                    b.HasKey("GiteNumber");

                    b.ToTable("tblGite");
                });

            modelBuilder.Entity("LegacyMonolith.Models.HotelRoom", b =>
                {
                    b.Property<int>("RoomNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomNumber"));

                    b.Property<int?>("CapacityMax")
                        .HasColumnType("int");

                    b.Property<int?>("CapacityMin")
                        .HasColumnType("int");

                    b.Property<decimal?>("HotelroomPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("bit");

                    b.HasKey("RoomNumber");

                    b.ToTable("tblHotelRoom");
                });

            modelBuilder.Entity("LegacyMonolith.Models.HotelRoomAmenities", b =>
                {
                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<bool?>("Balcony")
                        .HasColumnType("bit");

                    b.Property<bool?>("Bath")
                        .HasColumnType("bit");

                    b.Property<bool?>("Chair")
                        .HasColumnType("bit");

                    b.Property<bool?>("Cuttlery")
                        .HasColumnType("bit");

                    b.Property<bool?>("Desk")
                        .HasColumnType("bit");

                    b.Property<bool?>("Eatingarea")
                        .HasColumnType("bit");

                    b.Property<bool?>("Hairdryer")
                        .HasColumnType("bit");

                    b.Property<bool?>("Kettle")
                        .HasColumnType("bit");

                    b.Property<bool?>("Minifridge")
                        .HasColumnType("bit");

                    b.Property<bool?>("Roomservice")
                        .HasColumnType("bit");

                    b.Property<bool?>("Shower")
                        .HasColumnType("bit");

                    b.Property<bool?>("Smallchild")
                        .HasColumnType("bit");

                    b.Property<bool?>("Sofa")
                        .HasColumnType("bit");

                    b.Property<bool?>("Sofabed")
                        .HasColumnType("bit");

                    b.Property<bool?>("Toiletries")
                        .HasColumnType("bit");

                    b.Property<bool?>("Wifi")
                        .HasColumnType("bit");

                    b.HasKey("RoomNumber");

                    b.ToTable("tblHotelRoomAmenity");
                });

            modelBuilder.Entity("LegacyMonolith.Models.HotelRoomBed", b =>
                {
                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<int?>("Amount1PrBed")
                        .HasColumnType("int");

                    b.Property<int?>("Amount2PrBed")
                        .HasColumnType("int");

                    b.Property<int?>("Amount3PrBed")
                        .HasColumnType("int");

                    b.Property<string>("BedSort")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomNumber");

                    b.ToTable("tblHotelRoomBed");
                });

            modelBuilder.Entity("LegacyMonolith.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReservationEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservationStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReservationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReservationId");

                    b.HasIndex("AccountId");

                    b.ToTable("tblReservation");
                });

            modelBuilder.Entity("LegacyMonolith.Models.ReservationClient", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.HasKey("ReservationId", "Firstname", "Lastname");

                    b.ToTable("tblReservationClient");
                });

            modelBuilder.Entity("LegacyMonolith.Models.ReservationGite", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("GiteNumber")
                        .HasColumnType("int");

                    b.Property<int>("GiteDiscount")
                        .HasColumnType("int");

                    b.HasKey("ReservationId", "GiteNumber");

                    b.HasIndex("GiteNumber");

                    b.ToTable("tblReservationGite");
                });

            modelBuilder.Entity("LegacyMonolith.Models.ReservationHotel", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<int>("HotelroomDiscount")
                        .HasColumnType("int");

                    b.HasKey("ReservationId", "RoomNumber");

                    b.HasIndex("RoomNumber");

                    b.ToTable("tblReservationHotel");
                });

            modelBuilder.Entity("LegacyMonolith.Models.HotelRoomAmenities", b =>
                {
                    b.HasOne("LegacyMonolith.Models.HotelRoom", "Room")
                        .WithOne("Amenities")
                        .HasForeignKey("LegacyMonolith.Models.HotelRoomAmenities", "RoomNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("LegacyMonolith.Models.HotelRoomBed", b =>
                {
                    b.HasOne("LegacyMonolith.Models.HotelRoom", "Room")
                        .WithOne("Bed")
                        .HasForeignKey("LegacyMonolith.Models.HotelRoomBed", "RoomNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("LegacyMonolith.Models.Reservation", b =>
                {
                    b.HasOne("LegacyMonolith.Models.Account", "Account")
                        .WithMany("Reservations")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LegacyMonolith.Models.ReservationClient", b =>
                {
                    b.HasOne("LegacyMonolith.Models.Reservation", "Reservation")
                        .WithMany("ReservationClient")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("LegacyMonolith.Models.ReservationGite", b =>
                {
                    b.HasOne("LegacyMonolith.Models.Gite", "Gite")
                        .WithMany("ReservationGites")
                        .HasForeignKey("GiteNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegacyMonolith.Models.Reservation", "Reservation")
                        .WithMany("ReservationGite")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gite");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("LegacyMonolith.Models.ReservationHotel", b =>
                {
                    b.HasOne("LegacyMonolith.Models.Reservation", "Reservation")
                        .WithMany("ReservationHotel")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegacyMonolith.Models.HotelRoom", "Room")
                        .WithMany("ReservationHotels")
                        .HasForeignKey("RoomNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("LegacyMonolith.Models.Account", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LegacyMonolith.Models.Gite", b =>
                {
                    b.Navigation("ReservationGites");
                });

            modelBuilder.Entity("LegacyMonolith.Models.HotelRoom", b =>
                {
                    b.Navigation("Amenities")
                        .IsRequired();

                    b.Navigation("Bed")
                        .IsRequired();

                    b.Navigation("ReservationHotels");
                });

            modelBuilder.Entity("LegacyMonolith.Models.Reservation", b =>
                {
                    b.Navigation("ReservationClient");

                    b.Navigation("ReservationGite");

                    b.Navigation("ReservationHotel");
                });
#pragma warning restore 612, 618
        }
    }
}
