// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ReservationDbContext))]
    partial class ReservationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reservationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("accountId");

                    b.Property<decimal>("Discount")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("discount");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paymentStatus");

                    b.Property<DateTime>("ReservationEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("reservationEnd");

                    b.Property<decimal>("ReservationPrice")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("reservationPrice");

                    b.Property<DateTime>("ReservationStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("reservationStart");

                    b.Property<string>("ReservationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reservationStatus");

                    b.Property<decimal>("TouristTarif")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("touristTarif");

                    b.HasKey("ReservationId");

                    b.ToTable("tblReservation", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ReservationCamping", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservationId");

                    b.Property<int>("CampingId")
                        .HasColumnType("int")
                        .HasColumnName("campingId");

                    b.Property<decimal>("CampingDiscount")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("campingDiscount");

                    b.HasKey("ReservationId", "CampingId");

                    b.ToTable("tblReservationCamping", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ReservationClient", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservationId");

                    b.Property<string>("FirstName")
                        .HasColumnType("char(50)")
                        .HasColumnName("firstName")
                        .IsFixedLength();

                    b.Property<string>("LastName")
                        .HasColumnType("char(50)")
                        .HasColumnName("lastName")
                        .IsFixedLength();

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birthDate");

                    b.HasKey("ReservationId", "FirstName", "LastName");

                    b.ToTable("tblReservationClient", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ReservationFacility", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservationId");

                    b.Property<string>("Facility")
                        .HasColumnType("char(50)")
                        .HasColumnName("facility")
                        .IsFixedLength();

                    b.Property<decimal>("FacilityDiscount")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("facilityDiscount");

                    b.HasKey("ReservationId", "Facility");

                    b.ToTable("tblReservationFacility", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ReservationGite", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservationId");

                    b.Property<int>("GiteId")
                        .HasColumnType("int")
                        .HasColumnName("giteId");

                    b.Property<decimal>("GiteDiscount")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("giteDiscount");

                    b.HasKey("ReservationId", "GiteId");

                    b.ToTable("tblReservationGite", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ReservationHotelroom", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservationId");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("roomId");

                    b.Property<decimal>("HotelroomDiscount")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("hotelroomDiscount");

                    b.HasKey("ReservationId", "RoomId");

                    b.ToTable("tblReservationHotelroom", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ReservationRestaurant", b =>
                {
                    b.Property<int>("ReservationRestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reservationRestaurantId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationRestaurantId"));

                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservationId");

                    b.Property<decimal>("TableBill")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tableBill");

                    b.Property<decimal>("TableDiscount")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("tableDiscount");

                    b.Property<int>("TableId")
                        .HasColumnType("int")
                        .HasColumnName("tableId");

                    b.Property<DateTime>("TableReservationEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("tableReservationEnd");

                    b.Property<DateTime>("TableReservationStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("tableReservationStart");

                    b.HasKey("ReservationRestaurantId");

                    b.HasIndex("ReservationId");

                    b.ToTable("tblReservationRestaurant", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Vehicle", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservationId");

                    b.Property<string>("RegistrationPlate")
                        .HasColumnType("char(50)")
                        .HasColumnName("registrationPlate")
                        .IsFixedLength();

                    b.HasKey("ReservationId", "RegistrationPlate");

                    b.ToTable("tblVehicle", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ReservationCamping", b =>
                {
                    b.HasOne("Domain.Models.Reservation", "Reservation")
                        .WithMany("Campings")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Domain.Models.ReservationClient", b =>
                {
                    b.HasOne("Domain.Models.Reservation", "Reservation")
                        .WithMany("Clients")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Domain.Models.ReservationFacility", b =>
                {
                    b.HasOne("Domain.Models.Reservation", "Reservation")
                        .WithMany("Facilities")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Domain.Models.ReservationGite", b =>
                {
                    b.HasOne("Domain.Models.Reservation", "Reservation")
                        .WithMany("Gites")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Domain.Models.ReservationHotelroom", b =>
                {
                    b.HasOne("Domain.Models.Reservation", "Reservation")
                        .WithMany("Hotelrooms")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Domain.Models.ReservationRestaurant", b =>
                {
                    b.HasOne("Domain.Models.Reservation", "Reservation")
                        .WithMany("Restaurants")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Domain.Models.Vehicle", b =>
                {
                    b.HasOne("Domain.Models.Reservation", "Reservation")
                        .WithMany("Vehicles")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Domain.Models.Reservation", b =>
                {
                    b.Navigation("Campings");

                    b.Navigation("Clients");

                    b.Navigation("Facilities");

                    b.Navigation("Gites");

                    b.Navigation("Hotelrooms");

                    b.Navigation("Restaurants");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
