// <auto-generated />
using System;
using HotelProgramma.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelProgramma.Migrations
{
    [DbContext(typeof(DbMarconnes))]
    partial class DbMarconnesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelProgramma.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("HotelProgramma.Models.Gite", b =>
                {
                    b.Property<int>("GiteNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiteNumber"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("GiteAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GitePrice")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.HasKey("GiteNumber");

                    b.ToTable("Gites");
                });

            modelBuilder.Entity("HotelProgramma.Models.HotelRoom", b =>
                {
                    b.Property<int>("RoomNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomNumber"));

                    b.Property<int>("HotelroomPrice")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.HasKey("RoomNumber");

                    b.ToTable("HotelRooms");
                });

            modelBuilder.Entity("HotelProgramma.Models.HotelRoomAmenities", b =>
                {
                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<bool?>("Balcony")
                        .HasColumnType("bit");

                    b.Property<bool?>("Bath")
                        .HasColumnType("bit");

                    b.Property<bool?>("Chair")
                        .HasColumnType("bit");

                    b.Property<bool?>("Cuttlery")
                        .HasColumnType("bit");

                    b.Property<bool?>("Desk")
                        .HasColumnType("bit");

                    b.Property<bool?>("Eatingarea")
                        .HasColumnType("bit");

                    b.Property<bool?>("Hairdryer")
                        .HasColumnType("bit");

                    b.Property<bool?>("Kettle")
                        .HasColumnType("bit");

                    b.Property<bool?>("Minifridge")
                        .HasColumnType("bit");

                    b.Property<bool?>("Roomservice")
                        .HasColumnType("bit");

                    b.Property<bool?>("Shower")
                        .HasColumnType("bit");

                    b.Property<bool?>("Smallchild")
                        .HasColumnType("bit");

                    b.Property<bool?>("Sofa")
                        .HasColumnType("bit");

                    b.Property<bool?>("Sofabed")
                        .HasColumnType("bit");

                    b.Property<bool?>("Toiletries")
                        .HasColumnType("bit");

                    b.Property<bool?>("Wifi")
                        .HasColumnType("bit");

                    b.HasKey("RoomNumber");

                    b.ToTable("HotelRoomAmenities");
                });

            modelBuilder.Entity("HotelProgramma.Models.HotelRoomBed", b =>
                {
                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<int>("Amount1PrBed")
                        .HasColumnType("int");

                    b.Property<int>("Amount2PrBed")
                        .HasColumnType("int");

                    b.Property<int>("Amount3PrBed")
                        .HasColumnType("int");

                    b.Property<string>("BedSort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomNumber");

                    b.ToTable("HotelRoomBeds");
                });

            modelBuilder.Entity("HotelProgramma.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReservationEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservationStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReservationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReservationId");

                    b.HasIndex("AccountId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("HotelProgramma.Models.ReservationClient", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.HasKey("ReservationId", "Firstname", "Lastname");

                    b.ToTable("ReservationClients");
                });

            modelBuilder.Entity("HotelProgramma.Models.ReservationGite", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("GiteNumber")
                        .HasColumnType("int");

                    b.Property<int>("GiteDiscount")
                        .HasColumnType("int");

                    b.HasKey("ReservationId", "GiteNumber");

                    b.HasIndex("GiteNumber");

                    b.ToTable("ReservationGites");
                });

            modelBuilder.Entity("HotelProgramma.Models.ReservationHotel", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<int>("HotelroomDiscount")
                        .HasColumnType("int");

                    b.HasKey("ReservationId", "RoomNumber");

                    b.HasIndex("RoomNumber");

                    b.ToTable("ReservationHotels");
                });

            modelBuilder.Entity("HotelProgramma.Models.HotelRoomAmenities", b =>
                {
                    b.HasOne("HotelProgramma.Models.HotelRoom", "Room")
                        .WithOne("Amenities")
                        .HasForeignKey("HotelProgramma.Models.HotelRoomAmenities", "RoomNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelProgramma.Models.HotelRoomBed", b =>
                {
                    b.HasOne("HotelProgramma.Models.HotelRoom", "Room")
                        .WithOne("Bed")
                        .HasForeignKey("HotelProgramma.Models.HotelRoomBed", "RoomNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelProgramma.Models.Reservation", b =>
                {
                    b.HasOne("HotelProgramma.Models.Account", "Account")
                        .WithMany("Reservations")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("HotelProgramma.Models.ReservationClient", b =>
                {
                    b.HasOne("HotelProgramma.Models.Reservation", "Reservation")
                        .WithMany("Clients")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelProgramma.Models.ReservationGite", b =>
                {
                    b.HasOne("HotelProgramma.Models.Gite", "Gite")
                        .WithMany("ReservationGites")
                        .HasForeignKey("GiteNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelProgramma.Models.Reservation", "Reservation")
                        .WithMany("Gites")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gite");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelProgramma.Models.ReservationHotel", b =>
                {
                    b.HasOne("HotelProgramma.Models.Reservation", "Reservation")
                        .WithMany("Hotels")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelProgramma.Models.HotelRoom", "Room")
                        .WithMany("ReservationHotels")
                        .HasForeignKey("RoomNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelProgramma.Models.Account", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("HotelProgramma.Models.Gite", b =>
                {
                    b.Navigation("ReservationGites");
                });

            modelBuilder.Entity("HotelProgramma.Models.HotelRoom", b =>
                {
                    b.Navigation("Amenities")
                        .IsRequired();

                    b.Navigation("Bed")
                        .IsRequired();

                    b.Navigation("ReservationHotels");
                });

            modelBuilder.Entity("HotelProgramma.Models.Reservation", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Gites");

                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
